free_sample can generate scripts

diff --git a/bin/free_sample b/bin/free_sample
--- a/bin/free_sample
+++ b/bin/free_sample
@@ -4,8 +4,7 @@
 #/     free_sample -- template for a meaty script
 #/
 #/ SYNOPSIS
-#/     free_sample
-#/     free_sample -n David
+#/     free_sample script_name
 
 # figure out the project root under which bin, lib live
 shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"
@@ -13,22 +12,30 @@ shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"
 # load a meat library
 source "$shome/bin/_prime" "$@"
 
-# pull in extra libraries
-require "free_sample"
-
 # entry point
 function main {
-  # say Hello!
-  echo "Hello, ${FLAGS_name}!"
+  local nm_script="$1"; shift
+
+  tmp_script="$(mktemp -t XXXXXXXXX)"
+  cat "$shome/bin/$(basename "$0")" | sed "s#free_sample#$nm_script#" > "$tmp_script"
+  mv "$tmp_script" "$shome/bin/$nm_script.new"
+  chmod 755 "$shome/bin/$nm_script.new"
+  mv "$shome/bin/$nm_script.new" "$shome/bin/$nm_script"
 }
 
 # define command line options:
 #   var name, default, description, short option
-DEFINE_string 'name' 'World' 'name to say hello to' 'n'
+DEFINE_string 'name' '' 'generate script name' '-n'
 
 # parse the command-line
 parse_command_line "$@" || exit $?
 eval set -- "${FLAGS_ARGV}"
+
+if [[ "$#" = 0 ]]; then
+  echo "ERROR: missing script name"
+  display_help
+  exit 1
+fi
 
 # pass arguments to entry point
 main "$@"
