put $shome/bin into PATH

diff --git a/lib/_meat b/lib/_meat
--- a/lib/_meat
+++ b/lib/_meat
@@ -1,14 +1,5 @@
 #!/bin/bash
 
-if [[ "$0" = "-bash" ]]; then
-  echo 'ERROR: cannot source library without setting $shome'
-  exit 1
-fi
-
-if [[ -z "$shome" ]]; then
-  shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"
-fi
-  
 function check_help {
   # taken from shocco
   if expr -- "$*" : ".*--help" >/dev/null; then
@@ -16,3 +7,18 @@ function check_help {
     exit 0
   fi
 }
+
+function _main {
+  if [[ "$0" = "-bash" ]]; then
+    echo 'ERROR: cannot source library without setting $shome'
+    exit 1
+  fi
+
+  if [[ -z "$shome" ]]; then
+    shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"
+  fi
+
+  PATH="$shome/bin:$PATH"
+}
+
+_main "$@"
